#!/usr/bin/env python3

// Connect to the MongoDB server
db.adminCommand({ listDatabases: 1 }).databases.forEach(function(database) {
    print(database.name + "\t" + database.sizeOnDisk / (1024 * 1024 * 1024) + "GB");
});

