#!/usr/bin/env python3

// Add the 'address' attribute with the value '972 Mission street' to the document with name="Holberton school"
db.school.updateMany(
  { name: "Holberton school" },
  { $set: { address: "972 Mission street" } }
)
